[build]
rustflags = ["-C", "link-arg=-undefined", "-C", "linker=clang"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "linker=clang"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "linker=clang"]
