import SwiftUI
import MetalKit
import Combine

// Import the generated FFI bindings
import OpalCore

@main
struct OpalApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
        .windowStyle(.hiddenTitleBar)
        .commands {
            OpalCommands()
        }
    }
}

class AppDelegate: NSObject, NSApplicationDelegate {
    func applicationDidFinishLaunching(_ notification: Notification) {
        // Ensure proper menu bar setup
        setupMenuBar()
    }
    
    func setupMenuBar() {
        // Main menu is auto-generated by SwiftUI, but we can customize if needed
    }
}

struct OpalCommands: Commands {
    @State private var showingSettings = false
    
    var body: some Commands {
        // Replace standard preferences command
        CommandGroup(replacing: .appSettings) {
            Button("Settings...") {
                openSettings()
            }
            .keyboardShortcut(",", modifiers: .command)
        }
        
        CommandMenu("Terminal") {
            Button("New Tab") {
                NotificationCenter.default.post(name: .newTab, object: nil)
            }
            .keyboardShortcut("t", modifiers: .command)
            
            Button("Close Tab") {
                NotificationCenter.default.post(name: .closeTab, object: nil)
            }
            .keyboardShortcut("w", modifiers: .command)
            
            Divider()
            
            Button("Clear Screen") {
                NotificationCenter.default.post(name: .clearScreen, object: nil)
            }
            .keyboardShortcut("k", modifiers: .command)
        }
        
        CommandMenu("View") {
            Button("Toggle Sidebar") {
                NotificationCenter.default.post(name: .toggleSidebar, object: nil)
            }
            .keyboardShortcut("s", modifiers: [.command, .shift])
            
            Button("Command Palette") {
                NotificationCenter.default.post(name: .showCommandPalette, object: nil)
            }
            .keyboardShortcut("p", modifiers: [.command, .shift])
            
            Divider()
            
            Button("Enter Full Screen") {
                NSApp.keyWindow?.toggleFullScreen(nil)
            }
            .keyboardShortcut("f", modifiers: [.command, .control])
        }
        
        CommandMenu("Window") {
            Button("Minimize") {
                NSApp.keyWindow?.miniaturize(nil)
            }
            .keyboardShortcut("m", modifiers: .command)
            
            Button("Zoom") {
                NSApp.keyWindow?.zoom(nil)
            }
        }
    }
    
    private func openSettings() {
        // Create and show settings window
        let settingsWindow = NSWindow(
            contentRect: NSRect(x: 0, y: 0, width: 700, height: 500),
            styleMask: [.titled, .closable, .miniaturizable, .resizable],
            backing: .buffered,
            defer: false
        )
        settingsWindow.title = "Settings"
        settingsWindow.contentView = NSHostingView(rootView: SettingsView())
        settingsWindow.center()
        settingsWindow.makeKeyAndOrderFront(nil)
    }
}

// Notification names for menu actions
extension Notification.Name {
    static let newTab = Notification.Name("newTab")
    static let closeTab = Notification.Name("closeTab")
    static let clearScreen = Notification.Name("clearScreen")
    static let toggleSidebar = Notification.Name("toggleSidebar")
    static let showCommandPalette = Notification.Name("showCommandPalette")
}
